# Whisper Model
model: "large-v3"
prompt: "The person is a swiss professor teaching online school."
language: "de"

# Recording Settings
save_path: "recordings"
default_device: "Echo Cancelling Speakerphone (PHL 49B2U6900CH)"
segment_duration: 60
